### ISSUE TITLE
Plugin fails to work with Safari Version 11.0.2 (13604.4.7.1.3)

### ISSUE THREAD

**Issue by ralfEdmund** [thiagopnts/kaleidoscope#33] opened 2018-01-16 23:05 UTC
Images and Videos are invisible on Version 11.0.2 (13604.4.7.1.3) of Safari

**Comment by thiagopnts** [comment] 2018-01-31 22:21
Weird, I can't reproduce but I'm on 11.0.3

**Comment by thiagopnts** [comment] 2018-04-26 19:46
closing since it seems to be specific to a patch version

**Closed by thiagopnts** 2018-04-26 19:46 UTC
